export const CHANGE_MINUTES_INTERVAL_VALUE = 'CHANGE_MINUTES_INTERVAL_VALUE';
export const CHANGE_HOURS_INTERVAL_VALUE = 'CHANGE_HOURS_INTERVAL_VALUE';
export const CHANGE_WEEKDAYS_INTERVAL_VALUE = 'CHANGE_WEEKDAYS_INTERVAL_VALUE';
export const CHANGE_MONTHDAYS_INTERVAL_VALUE = 'CHANGE_MONTHDAYS_INTERVAL_VALUE';
export const CHANGE_MONTHS_INTERVAL_VALUE = 'CHANGE_MONTHS_INTERVAL_VALUE';
export const CLEAR_INTERVAL_VALUE = 'CLEAR_INTERVAL_VALUE';

export const CHANGE_WEEKDAY_VALUE = 'CHANGE_WEEKDAY_VALUE';
export const CHANGE_WEEKDAY_VISIBILITY = 'CHANGE_WEEKDAY_VISIBILITY';
export const CLEAR_WEEKDAY_VALUE = 'CLEAR_WEEKDAY_VALUE';

export const CHANGE_MINUTES_VALUE = 'CHANGE_MINUTES_VALUE';
export const CHANGE_MINUTES_VISIBILITY = 'CHANGE_MINUTES_VISIBILITY';
export const CLEAR_MINUTES_VALUE = 'CLEAR_MINUTES_VALUE';

export const CHANGE_HOURS_VALUE = 'CHANGE_HOURS_VALUE';
export const CHANGE_HOURS_VISIBILITY = 'CHANGE_HOURS_VISIBILITY';
export const CLEAR_HOURS_VALUE = 'CLEAR_HOURS_VALUE';

export const CHANGE_MONTHDAY_VALUE = 'CHANGE_MONTHDAY_VALUE';
export const CHANGE_MONTHDAY_VISIBILITY = 'CHANGE_MONTHDAY_VISIBILITY';
export const CLEAR_MONTHDAY_VALUE = 'CLEAR_MONTHDAY_VALUE';

export const CHANGE_MONTHS_VALUE = 'CHANGE_MONTHS_VALUE';
export const CHANGE_MONTHS_VISIBILITY = 'CHANGE_MONTHS_VISIBILITY';
export const CLEAR_MONTHS_VALUE = 'CLEAR_MONTHS_VALUE';
